# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       NODE_ENV: production
#     volumes:
#       - .:/app
#     command: pnpm start

services:
  next-15-app-route:
    build:
      context: ./
      dockerfile: Dockerfile
    image: next-15-app-route
    ports:
      - "3000:3000"