name: "Deploy Simple"

on:
  workflow_dispatch:

env:
  working-directory: .
  app-service-name: next-15-app-route-ttss # Ensure this matches your Azure app service name
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }} # Ensure this secret is set on github actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x" # Ensure this is the desired Node.js version

      - name: Enable Corepack and Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm run build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone
          
      - name: List build directory contents
        run: ls -R ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.app-service-name }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./build/standalone
