name: "Deploy Simple"

on:
  workflow_dispatch:

env:
  working-directory: .
  app-service-name: next-15-app-route-ttss # Ensure this matches your Azure app service name
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }} # Ensure this secret is set on github actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x" # Ensure this is the desired Node.js version

      - name: Enable Corepack and Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm run build
          mv ${{ env.working-directory }}/build/static ${{ env.working-directory }}/build/standalone/build
          mv ${{ env.working-directory }}/public ${{ env.working-directory }}/build/standalone
        working-directory: ${{ env.working-directory }}

      - name: List build directory contents
        run: ls -R ${{ env.working-directory }}/build
        working-directory: ${{ env.working-directory }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.working-directory }}/build/standalone
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: webapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.app-service-name }}
          slot-name: production
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ${{ env.working-directory }}/build/standalone/build
